[package]
name = "rstd-cppstd"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-cppstd"
module = "rstd.cppstd"
archive = "rstd.cppstd"
sources = [
  "cppstd.cppm",
  "iter.cppm",
  "rstd.cppm",
]

[dependencies.rstd-std]
path = "../.."
version = "0.1.0"
pub = true
