[package]
name = "rstd-cppstd"
version.workspace = true

[lib]
name = "rstd-cppstd"
module = "rstd.cppstd"
archive = "rstd.cppstd"
discovery = "explicit"
sources = [
  "cppstd.cppm",
  "iter.cppm",
  "rstd.cppm",
]

[dependencies.rstd-std]
path = "../.."
visibility = "public"
