[package]
name = "rstd-dlopn"
version.workspace = true
target = { os = "linux" }

[lib]
name = "rstd-dlopn"
module = "rstd.dlopn"
archive = "rstd.dlopn"
discovery = "explicit"
sources = ["mod.cppm", "dlopn.cpp"]

[usage]
private-linker-options = ["-ldl"]

[dependencies.rstd-std]
path = "../.."
visibility = "public"
