[package]
name = "rstd-dlopn"
version.workspace = true
target = { os = "linux" }

[lib]
name = "rstd-dlopn"
module = "rstd.dlopn"
archive = "rstd.dlopn"
sources = ["mod.cppm", "dlopn.cpp"]

[usage]
system-libraries = ["dl"]

[dependencies.rstd-std]
path = "../.."
visibility = "public"
