[package]
name = "rstd-argparse"
version.workspace = true

[lib]
name = "rstd-argparse"
module = "rstd.argparse"
archive = "rstd.argparse"

[dependencies.rstd-std]
path = "../.."
visibility = "public"
