[package]
name = "rstd-argparse"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-argparse"
module = "rstd.argparse"
archive = "rstd.argparse"

[dependencies]
rstd-std = { workspace = true, pub = true }
