[workspace]
name = "rstd"
members = [
  "src/basic",
  "src/runtime",
  "src/core",
  "src/alloc",
  "src/parse",
  "src/serde",
  "src/argparse",
  "src/std",
  "src/bench",
  "src/test",
  "src/cppstd",
  "src/json",
  "src/toml",
  "src/log",
  "src/dlopn",
  "src/nostd",
]

[workspace.package]
version = "0.1.0"
license = "MIT OR Apache-2.0"

[profile]
exceptions = false
rtti = false
