[workspace]
name = "rstd"
members = [
  "src/basic",
  "src/runtime",
  "src/core",
  "src/alloc",
  "src/argparse",
  "src/std",
  "src/bench",
  "src/test",
  "src/cppstd",
  "src/json",
  "src/toml",
  "src/log",
  "src/dlopn",
  "src/nostd",
  "bench",
  "test",
  "test/dlopn-runtime",
  "test/compile_fail",
  "test/nostd",
  "test/toml",
]
default-members = ["bench"]

[workspace.package]
version = "0.1.0"
