[package]
name = "rstd-runtime"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-runtime"
module = "rstd.runtime"
archive = "rstd.runtime"

[dependencies.rstd-basic]
path = "../.."
version = "0.1.0"
visibility = "public"
