[package]
name = "rstd-json"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-json"
module = "rstd.json"
archive = "rstd.json"

[dependencies]
rstd-core = { workspace = true, pub = true }
rstd-std = { workspace = true, pub = true }
rstd-serde = { workspace = true, pub = true }
rstd-parse = { workspace = true }
