[package]
name = "rstd-json"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-json"
module = "rstd.json"
archive = "rstd.json"

[dependencies.rstd-core]
path = "../.."
version = "0.1.0"
pub = true

[dependencies.rstd-std]
path = "../.."
version = "0.1.0"
pub = true

[dependencies.rstd-serde]
path = "../serde"
version = "0.1.0"
pub = true

[dependencies.rstd-parse]
path = "../parse"
version = "0.1.0"
