[package]
name = "rstd-alloc"
version.workspace = true

[lib]
name = "rstd-alloc"
module = "rstd.alloc"
archive = "rstd.alloc"

[dependencies.rstd-core]
path = "../.."
visibility = "public"

[dependencies.rstd-runtime]
path = "../.."
visibility = "private"
