[package]
name = "rstd-serde"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-serde"
module = "rstd.serde"
archive = "rstd.serde"

[dependencies]
rstd-alloc = { workspace = true, pub = true }
