[package]
name = "rstd-toml"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-toml"
module = "rstd.toml"
archive = "rstd.toml"

[dependencies.rstd-alloc]
path = "../.."
version = "0.1.0"
visibility = "public"

[dependencies.rstd-core]
path = "../.."
version = "0.1.0"
visibility = "public"

[dependencies.rstd-serde]
path = "../serde"
version = "0.1.0"
visibility = "public"

[dependencies.rstd-parse]
path = "../parse"
version = "0.1.0"
visibility = "private"
