[package]
name = "rstd-toml"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-toml"
module = "rstd.toml"
archive = "rstd.toml"

[dependencies]
rstd-alloc = { workspace = true, pub = true }
rstd-core = { workspace = true, pub = true }
rstd-serde = { workspace = true, pub = true }
rstd-parse = { workspace = true }
