[package]
name = "rstd-toml"
version.workspace = true

[lib]
name = "rstd-toml"
module = "rstd.toml"
archive = "rstd.toml"
discovery = "module"

[usage]
private-options = [
  "-fPIC",
  "-Wall",
  "-Wpedantic",
  "-Wno-gnu-statement-expression",
  "-Wno-deprecated-declarations",
  "-Wunknown-attributes",
  "-fsized-deallocation",
]

[dependencies.rstd-alloc]
path = "../.."
visibility = "public"

[dependencies.rstd-core]
path = "../.."
visibility = "public"
