[package]
name = "rstd-bench"
version.workspace = true

[lib]
name = "rstd-bench"
module = "rstd.bench"
archive = "rstd.bench"
discovery = "module"

[dependencies.rstd-std]
path = "../.."
visibility = "public"
