[package]
name = "rstd-parse"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-parse"
module = "rstd.parse"
archive = "rstd.parse"

[dependencies.rstd-core]
path = "../.."
version = "0.1.0"
visibility = "public"

[dependencies.rstd-alloc]
path = "../.."
version = "0.1.0"
visibility = "public"
