[package]
name = "rstd-basic"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-basic"
module = "rstd.basic"
archive = "rstd.basic"

[usage]
public-include-directories = ["include"]
