[package]
name = "rstd-basic"
version.workspace = true
module = "rstd.basic"

[library]
archive = "rstd.basic"
discovery = "module"

[usage]
private-options = [
  "-fPIC",
  "-Wall",
  "-Wpedantic",
  "-Wno-gnu-statement-expression",
  "-Wno-deprecated-declarations",
  "-Wunknown-attributes",
  "-fsized-deallocation",
]
