[package]
name = "rstd-core"
version.workspace = true

[lib]
name = "rstd-core"
module = "rstd.core"
archive = "rstd.core"

[usage]
public-include-directories = ["include"]
[dependencies.rstd-basic]
path = "../.."
visibility = "public"

[dependencies.rstd-runtime]
path = "../.."
visibility = "private"
