[package]
name = "rstd-core"
version.workspace = true
module = "rstd.core"

[library]
archive = "rstd.core"
discovery = "module"

[usage]
public-include-directories = ["include"]
private-options = [
  "-fPIC",
  "-Wall",
  "-Wpedantic",
  "-Wno-gnu-statement-expression",
  "-Wno-deprecated-declarations",
  "-Wunknown-attributes",
  "-fsized-deallocation",
]

[dependencies.rstd-basic]
path = "../.."
visibility = "public"

[dependencies.rstd-runtime]
path = "../.."
visibility = "private"
