[package]
name = "rstd-std"
version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rstd-std"
module = "rstd"
archive = "rstd"

[dependencies.rstd-core]
path = "../.."
version = "0.1.0"
pub = true

[dependencies.rstd-alloc]
path = "../.."
version = "0.1.0"
pub = true
