[package]
name = "rstd-std"
version.workspace = true

[lib]
name = "rstd-std"
module = "rstd"
archive = "rstd"
discovery = "module"

[dependencies.rstd-core]
path = "../.."
visibility = "public"

[dependencies.rstd-alloc]
path = "../.."
visibility = "public"
