[package]
name = "rstd-std"
version.workspace = true
module = "rstd"

[library]
archive = "rstd"
discovery = "module"

[usage]
private-options = [
  "-fPIC",
  "-Wall",
  "-Wpedantic",
  "-Wno-gnu-statement-expression",
  "-Wno-deprecated-declarations",
  "-Wunknown-attributes",
  "-fsized-deallocation",
]

[dependencies.rstd-core]
path = "../.."
visibility = "public"

[dependencies.rstd-alloc]
path = "../.."
visibility = "public"
