[package]
name = "rstd-std"
version.workspace = true
module = "rstd"

[library]
archive = "rstd"
discovery = "explicit"
sources = [
  "alloc.cppm",
  "async/completion/completion.cppm",
  "async/completion/completion_queue.cppm",
  "async/core/atomic_waker.cppm",
  "async/core/awaitable.cppm",
  "async/core/facility.cppm",
  "async/core/forward.cppm",
  "async/core/task.cppm",
  "async/core/terminal.cppm",
  "async/future/join.cppm",
  "async/future/select.cppm",
  "async/io/io.cppm",
  "async/io/io_operation.cppm",
  "async/io/poll.cppm",
  "async/io/reactor.cppm",
  "async/io/readiness.cppm",
  "async/mod.cppm",
  "async/runtime/coro_driver.cppm",
  "async/runtime/executor.cppm",
  "async/runtime/runtime.cppm",
  "async/runtime/runtime_core.cppm",
  "async/runtime/runtime_driver.cppm",
  "async/runtime/spawn.cppm",
  "async/runtime/thread_pool_executor.cppm",
  "async/sync/notify.cppm",
  "async/sync/oneshot.cppm",
  "async/time/time.cppm",
  "async/time/timer_facility.cppm",
  "bytes/mod.cppm",
  "env.cpp",
  "env.cppm",
  "error.cppm",
  "ffi/mod.cppm",
  "ffi/os_str.cppm",
  "forward.cppm",
  "fs.cpp",
  "fs.cppm",
  "fs/types.cppm",
  "io/buffered.cppm",
  "io/cursor.cppm",
  "io/error.cpp",
  "io/error.cppm",
  "io/mod.cppm",
  "io/range.cppm",
  "io/stdio.cppm",
  "io/traits.cppm",
  "io/util.cppm",
  "mod.cpp",
  "mod.cppm",
  "net/mod.cppm",
  "net/socket_addr.cppm",
  "net/tcp.cpp",
  "net/tcp.cppm",
  "os/fd.cpp",
  "os/fd.cppm",
  "os/handle.cpp",
  "os/handle.cppm",
  "os/mod.cppm",
  "os/socket.cpp",
  "os/socket.cppm",
  "panicking.cppm",
  "path.cppm",
  "process/command.cppm",
  "process/exit_status.cppm",
  "process/mod.cppm",
  "process/process.cpp",
  "sync/condvar.cppm",
  "sync/mod.cppm",
  "sync/mpsc/mod.cppm",
  "sync/mpsc/mpmc/array.cppm",
  "sync/mpsc/mpmc/context.cppm",
  "sync/mpsc/mpmc/counter.cppm",
  "sync/mpsc/mpmc/error.cppm",
  "sync/mpsc/mpmc/list.cppm",
  "sync/mpsc/mpmc/mod.cppm",
  "sync/mpsc/mpmc/select.cppm",
  "sync/mpsc/mpmc/utils.cppm",
  "sync/mpsc/mpmc/waker.cppm",
  "sync/mpsc/mpmc/zero.cppm",
  "sync/mutex.cppm",
  "sync/once.cppm",
  "sync/poison/mod.cppm",
  "sys/fs.cppm",
  "sys/io/mod.cppm",
  "sys/io/stdio.cppm",
  "sys/libc/libc.cppm",
  "sys/libc/linux.cppm",
  "sys/libc/mod.cppm",
  "sys/libc/pthread.cppm",
  "sys/libc/unix.cppm",
  "sys/libc/windows.cppm",
  "sys/mod.cppm",
  "sys/pal/linux/io_uring.cppm",
  "sys/pal/linux/poll.cppm",
  "sys/pal/mod.cppm",
  "sys/pal/poll.cppm",
  "sys/pal/poll_types.cppm",
  "sys/pal/unix/futex.cpp",
  "sys/pal/unix/futex.cppm",
  "sys/pal/unix/mod.cppm",
  "sys/pal/unix/socket.cppm",
  "sys/pal/unix/sync/condvar.cppm",
  "sys/pal/unix/sync/mod.cppm",
  "sys/pal/unix/sync/mutex.cppm",
  "sys/pal/unix/time.cppm",
  "sys/pal/windows/futex.cpp",
  "sys/pal/windows/futex.cppm",
  "sys/pal/windows/mod.cppm",
  "sys/pal/windows/poll.cppm",
  "sys/pal/windows/socket.cppm",
  "sys/pal/windows/sync/condvar.cppm",
  "sys/pal/windows/sync/mod.cppm",
  "sys/pal/windows/sync/mutex.cppm",
  "sys/pal/windows/time.cppm",
  "sys/socket.cppm",
  "sys/sync/condvar/futex.cppm",
  "sys/sync/condvar/mod.cppm",
  "sys/sync/condvar/pthread.cppm",
  "sys/sync/mutex/futex.cppm",
  "sys/sync/mutex/mod.cppm",
  "sys/sync/mutex/pthread.cppm",
  "sys/sync/once/futex.cpp",
  "sys/sync/once/futex.cppm",
  "sys/sync/once/mod.cppm",
  "sys/sync/once_box.cppm",
  "sys/sync/thread_parking/futex.cpp",
  "sys/sync/thread_parking/futex.cppm",
  "sys/sync/thread_parking/mod.cppm",
  "sys/sync/thread_parking/pthread.cpp",
  "sys/sync/thread_parking/pthread.cppm",
  "sys/thread/mod.cppm",
  "sys/thread/unix.cppm",
  "sys/thread/windows.cppm",
  "thread/blocking_task_group.cppm",
  "thread/blocking_task_set.cppm",
  "thread/builder.cppm",
  "thread/current.cppm",
  "thread/forward.cppm",
  "thread/functions.cppm",
  "thread/id.cppm",
  "thread/join_handle.cppm",
  "thread/lifecycle.cppm",
  "thread/main_thread.cppm",
  "thread/mod.cppm",
  "thread/scoped.cppm",
  "thread/thread.cpp",
  "thread/thread.cppm",
  "thread/thread_pool.cppm",
  "time.cppm",
  "time/calendar.cppm",
]

[usage]
private-options = [
  "-fPIC",
  "-Wall",
  "-Wpedantic",
  "-Wno-gnu-statement-expression",
  "-Wno-deprecated-declarations",
  "-Wunknown-attributes",
  "-fsized-deallocation",
]

[dependencies.rstd-core]
path = "../.."
visibility = "public"

[dependencies.rstd-alloc]
path = "../.."
visibility = "public"
